# Generated by Django 5.2.4 on 2025-12-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], default='new', max_length=255, null=True),
        ),
    ]
