# Generated by Django 5.2.4 on 2025-08-07 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('is_valid', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.job')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAuditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_h1', models.BooleanField(default=False)),
                ('mutiple_h1_count', models.IntegerField(default=0)),
                ('mutiple_h1_tags', models.JSONField(default=list)),
                ('missing_title', models.BooleanField(default=False)),
                ('missing_desc', models.BooleanField(default=False)),
                ('multiple_title_count', models.IntegerField(default=0)),
                ('multiple_title_tags', models.JSONField(default=list)),
                ('missing_alt', models.IntegerField(default=0)),
                ('missing_alt_tags', models.JSONField(default=list)),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrap_App.links')),
            ],
        ),
    ]
